---
- name: CIS Benchmark for CentOS 7
  hosts: all
  vars:
    - cis_level_1: 'yes'
    - cis_level_2: 'no'
    - cis_level_1_scored: 'yes'
    - cis_level_2_scored: 'no'

  tasks:

    # 1.1.1 Ensure mounting of cramfs filesystems is disabled
    - name: 1.1.1 Ensure mounting of cramfs filesystems is disabled
      mount:
        name: cramfs
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.2 Ensure mounting of freevxfs filesystems is disabled
    - name: 1.1.2 Ensure mounting of freevxfs filesystems is disabled
      mount:
        name: freevxfs
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.3 Ensure mounting of jffs2 filesystems is disabled
    - name: 1.1.3 Ensure mounting of jffs2 filesystems is disabled
      mount:
        name: jffs2
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.4 Ensure mounting of hfs filesystems is disabled
    - name: 1.1.4 Ensure mounting of hfs filesystems is disabled
      mount:
        name: hfs
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.5 Ensure mounting of hfsplus filesystems is disabled
    - name: 1.1.5 Ensure mounting of hfsplus filesystems is disabled
      mount:
        name: hfsplus
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.6 Ensure mounting of squashfs filesystems is disabled
    - name: 1.1.6 Ensure mounting of squashfs filesystems is disabled
      mount:
        name: squashfs
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.7 Ensure mounting of udf filesystems is disabled
    - name: 1.1.7 Ensure mounting of udf filesystems is disabled
      mount:
        name: udf
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.8 Ensure mounting of FAT filesystems is disabled
    - name: 1.1.8 Ensure mounting of FAT filesystems is disabled
      mount:
        name: vfat
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.9 Ensure mounting of squashfs filesystems is disabled
    - name: 1.1.9 Ensure mounting of squashfs filesystems is disabled
      mount:
        name: squashfs
        state: absent
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.10 Ensure noexec option set on /tmp partition
    - name: 1.1.10 Ensure noexec option set on /tmp partition
      mount:
        name: /tmp
        fstype: tmpfs
        opts: noexec
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.11 Ensure separate partition exists for /var
    - name: 1.1.11 Ensure separate partition exists for /var
      command: df -hP /var | grep -v Filesystem | awk '{print $6}' | grep -v '/var$'
      register: var_partition
      failed_when: False
      changed_when: False
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.12 Ensure separate partition exists for /var/tmp
    - name: 1.1.12 Ensure separate partition exists for /var/tmp
      command: df -hP /var/tmp | grep -v Filesystem | awk '{print $6}' | grep -v '/var/tmp$'
      register: var_tmp_partition
      failed_when: False
      changed_when: False
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.13 Ensure nodev option set on /var/tmp partition
    - name: 1.1.13 Ensure nodev option set on /var/tmp partition
      mount:
        name: /var/tmp
        opts: nodev
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)

    # 1.1.14 Ensure nosuid option set on /var/tmp partition
    - name: 1.1.14 Ensure nosuid option set on /var/tmp partition
      mount:
        name: /var/tmp
        opts: nosuid
      when: (cis_level_1|bool and cis_level_1_scored|bool) or (cis_level_2|bool and cis_level_2_scored|bool)
